services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example
    container_name: db
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    networks:
      - docker-network
 
  adminer:
    image: adminer
    restart: unless-stopped
    container_name: db-web-interface
    ports:
      - 8080:8080
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
